### ISSUE TITLE
Filename search is broken, tuple unpacking

### ISSUE THREAD

**Issue by AlexVallat** [jarmo/service.subtitles.subscene#4]
Is str() here right? It breaks unpacking of the getCleanMovieTitle result tuple...

https://github.com/jarmo/service.subtitles.subscene/blob/97e0f204e63d960ba1659ed78d0c5949022f1266/service.py#L353

**Comment by StefanRvO** [comment]
I got the same issue. Fixed if the str() call is removed. I don't see how it can work to unpack the stringified tuple.
