### ISSUE TITLE
Subtitles file for season of the series

### ISSUE THREAD

**Issue by iBasim** [jarmo/service.subtitles.subscene#7]
Subscene has a problem with arabic subtitles

Some subtitles are one file with subtitles for all episodes of the season and Kodi chooses subtitles
![IMG_20200610_043940](https://user-images.githubusercontent.com/57762287/84221710-88a1fb00-aade-11ea-817d-9bc2a7e677d5.jpg)

The problem is that some series cannot choose subtitles and some can
![ZomboDroid 10062020053726](https://user-images.githubusercontent.com/57762287/84221743-9c4d6180-aade-11ea-82df-24f9a6334527.jpg)

I tried more than one version of Subscene add-on and same problem

logs
https://paste.kodi.tv/ejajewisit.kodi

**Comment by jarmo** [comment]
Have not seen anything like this before and don't know how to even handle that kind of a situation. Leaving this issue open in case someone wants to dig into it and add support for that weird situation where a subtitles pack is offered instead of a single episode subtitle.

**Comment by jarmo** [comment]
Closing this due to archival of this repository.
